Fix: Set ONNX Options: Disable telemetry, limit threads, lower CPU usage, potential "memory leak"
Project-Babble/ProjectBabble pull request #55
Opened 2024-10-15 02:08 UTC by SnuffSocket

2024-10-17 23:08 UTC, dfgHiatus commented
Thanks for your PR! Could you please elaborate on what you mean by "potential memory leak"?

2024-10-18 22:34 UTC, RamesTheGeneric commented
Heya, what is the reason for hard coding the thread count at 1?

2024-10-18 23:08 UTC, dfgHiatus commented
I've added some feedback on your PR. As with Rames's comment, did you see any performance change(s) with a thread count of 1? Thanks again

2024-10-19 03:32 UTC, SnuffSocket commented
> Heya, what is the reason for hard coding the thread count at 1?

That's from me testing "ORT_PARALLEL" mode.
Restricting "inter_op_num_threads" didn't seem be the limiting factor, unlike "intra_op_num_threads".
And with default "0" and "ORT_SEQUENTIAL" the runtime decided it should be "1" anyway.

So to avoid any overhead with letting runtime decide what to set it, may as well set it ourselves?

2024-10-19 03:33 UTC, SnuffSocket commented
> I've added some feedback on your PR. As with Rames's comment, did you see any performance change(s) with a thread count of 1? Thanks again

I can't see the feedback?

2024-10-20 00:47 UTC, dfgHiatus commented
Oh, I have some pending changes I marked for review. You can see them under the "Files changed" tab

2024-10-20 02:04 UTC, SnuffSocket commented
Yeah I still can't see 'em, did you forget to submit them? :/

2024-10-20 02:06 UTC, dfgHiatus requested changes

2024-10-20 02:07 UTC, dfgHiatus commented
Aaand I did. That's two for two, sorry :>

2024-10-20 02:29 UTC, SnuffSocket commented on BabbleApp/landmark_processor.py
> +        self.opts.inter_op_num_threads = 1
I disagree as the current/default behaviour without it aka "0" sets it to 1, also the default "ORT_SEQUENTIAL" mode doesn't benefit from giving this more threads anyway..

2024-10-20 02:29 UTC, SnuffSocket commented on BabbleApp/babble_processor.py
>          self.opts.intra_op_num_threads = settings.gui_inference_threads
I disagree as the current/default behaviour without it aka "0" sets it to 1, also the default "ORT_SEQUENTIAL" mode doesn't benefit from giving this more threads anyway..

2024-10-21 20:45 UTC, dfgHiatus approved these changes

2024-10-21 20:45 UTC, merged